---
server:
  port: 3000
  logging: true
database:
  type: sqlite
  database: database/local.db
  synchronize: true
  logging: true
  entities:
  - src/entities/*.ts
  migrations:
  - src/migrations/**/*.ts
  subscribers:
  - src/subscribers/**/*.ts
